import "./globals.css";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import { Layout } from "@/components/layouts/app-layout";
import { Header } from "@/components/header";

import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					inter.className,
					"min-h-screen overscroll-none bg-background"
				)}
			>
				<Header />
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
